export const ApiToastCode = {
  USERNAME_NOT_FOUND: 'Username not found',
  PASSWORD_INCORRECT: 'Incorrect Password',
  USERNAME_NOT_AVAILABLE: 'Email already exists',
  USER_NOT_CREATED: 'Username not created',
  PHONE_NUMBER_USED: 'Phone number already used',
  PHONE_NUMBER_INVALID: 'Invalid phone number',
  VALIDATION_ERROR: 'Invalid input',
  TRIP_NOT_FOUND: 'Trip not found',
  INVALID_VERIFICATION_CODE: 'Verification code is invalid',
  INVALID_EMAIL_VERIFICATION_CODE: 'Verification code is invalid',
  USER_NOT_FOUND: 'User not found',
  ERROR_SHARE_FAILED: 'Error share failed',
  FEED_SHARE_SUCCESS: 'Feed share failed',
  SHARE_FAILED: 'Share failed',
  INVALID_REQUEST: 'Invalid request',
  FRIEND_REQUEST_PENDING: 'Friend request pending',
  ALREADY_FRIEND: 'Already a friend',
  FRIEND_REQUEST_SENT_FAILED: 'Friend request sending failed',
  NOTIFICATION_SEND_FAILED: 'Notification sending failed',
  FRIEND_REQUEST_SENT: 'Friend request sent',
  REQUEST_NOT_FOUND: 'Request not found',
  RELATION_CREATE_FAILED: 'Relation creation failed',
  REQUEST_UPDATE_FAILED: 'Request update failed',
  NOTIFICATION_SENT_FAILED: 'Notification sending failed',
  FRIEND_REQUEST_ACCEPTED: 'Friend request accepted',
  FRIEND_REQUEST_NOTIFICATION_NOT_FOUND: 'Friend request notification not found',
  REQUEST_DESTROY_FAILED: 'Request cancel failed',
  FRIEND_REQUEST_REJECTED: 'Friend request rejected',
  NOT_AUTHORIZED: 'Not authorized',
  FRIEND_REQUEST_CANCELLED: 'Friend request cancelled',
  REQUEST_FAILED: 'Request failed',
  ALREADY_GROUP_MEMBER: 'Already a group member',
  GROUP_NOT_FOUND: 'Group not found',
  ERROR_JOINING_GROUP: 'Error joining group',
  ERROR_CREATING_GROUP_MEMBERSHIP: 'Error creating group membership',
  NOTIFICATION_CREATE_FAILED: 'Notification creation failed',
  JOIN_GROUP_REQUEST_SENT: 'Join group request sent',
  GROUP_REQUEST_ACCEPT_FAILED: 'Join group request accept failed',
  REQUEST_ACCEPTED: 'Request accepted',
  GROUP_INVITATION_REJECT_FAILED: 'Group invitation rejection failed',
  REJECT_SUCCESS: 'Request rejected',
  ADMIN_NOT_FOUND: 'Admin not found',
  ONLY_ONE_ADMIN: 'Only one admin',
  LEAVE_GROUP_FAILED: 'Could not leave group',
  LEAVE_GROUP_SUCCESS: 'Left the group',
  NOTIFICATION_NOT_FOUND: 'Notification not found',
  NOTIFICATION_READ: 'Notification read',
  TRIP_CREATE_FAILED: 'Could not create trip',
  PHONE_NUMBER_REQUIRED: 'Phone number required to sync contact',
  USER_UPDATE_FAILED: 'Could not update user',
  EMAIL_VERIFIED: 'Email verified',
  EMAIL_VERIFICATION_CODE_EXPIRED: 'Your verification code has expired, please resend a new verification code.',
  EMAIL_NOT_AVAILABLE: 'Email not available',
  NEED_TO_PARTICIPATE_IN_GROUP_TO_SHARE_LOCATION: 'You are not a participant.',
};

export const AppToastCode = {
  TO_REQUIRED: 'To is required',
  FROM_REQUIRED: 'From is required',
  EMAIL_REQUIRED: 'Email is required',
  USERNAME_REQUIRED: 'Username is required',
  EMAIL_VERIFICATION_CODE_REQUIRED: 'Verification code is required',
  FIRST_NAME_REQUIRED: 'First name is required.',
  LAST_NAME_REQUIRED: 'Last name is required.',
  PHONE_REQUIRED: 'Phone is required.',
  PASSWORD_REQUIRED: 'Password is required.',
  PHONE_NUMBER_NOT_VERIFIED: 'Phone number not verified',
  PHONE_NUMBER_VERIFIED: 'Phone number verified',
  COUNTRY_CODE_REQUIRED: 'Country code is required.',
  COUNTRY_REQUIRED: 'Country is required',
  MUNICIPALITY_REQUIRED: 'Municipality is required',
  GROUP_NAME_REQUIRED: 'Group name is required',
  COMMENT_ADDED: 'Comment successfully added',
  COMMENT_REQUIRED: 'Comment required',
  SEAT_REQUIRED: 'No. of seat must be atleast one',
  DESCRIPTION_REQUIRED: 'Description is required',
  DATE_REQUIRED: 'Date is required.',
  TIME_REQUIRED: 'Time is required.',
  INVALID_TIME: 'Time must be greater than current time',
  PASSWORD_UPDATED: 'Password successfully updated.',
  ENTER_NEW_PASSWORD: 'Please enter new password.',
  ENTER_OLD_PASSWORD: 'Please enter old password.',
  PASSWORD_UNMATCH: 'New passwords do not match.',
  ENTER_CONFIRM_PASSWORD: 'Please enter confirm password.',
  PASSWORD_SHORT: 'New password too short, should be atleast 5 characters.',
  PROFILE_UPDATED: 'Profile successfully updated.',
  GROUP_PHOTO_REQUIRED: 'Group photo is required',
  EMAIL_VERIFICATION_CODE_RESENT: 'Verification code resent.',
  ERROR_RESENDING_EMAIL_VERIFICATION: 'Error sending verification code! Please Retry.',
  EMAIL_SUCCESSFULLY_CHANGED: 'Your e-mail has been updated. Please check your e-mail and click the link to verify.',
  PHONE_NUMBER_SUCCESSFULLY_CHANGED: 'Your phone number has been updated. Please verify your new phone number to set it as a default phone number.',
  SELECT_ONE_RIDE: 'Please select on ride to suggest.',
  SELECT_ONE_USER: 'Please select at least one user to add.',
};
