export const ToastCode = {
  USERNAME_NOT_FOUND: 'Username not found',
  PASSWORD_INCORRECT: 'Incorrect Password',
  USERNAME_NOT_AVAILABLE: 'Email already exists',
  USERNAME_REQUIRED: 'Username is required',
  USER_NOT_CREATED: 'Username not created',
  PHONE_NUMBER_USED: 'Phone number already used',
  PHONE_NUMBER_INVALID: 'Invalid phone number',
  VALIDATION_ERROR: 'Invalid input',
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_VERIFICATION_CODE_REQUIRED: 'Verification code is required',
  TRIP_NOT_FOUND: 'Trip not found',
  FIRST_NAME_REQUIRED: 'First Name is required.',
  LAST_NAME_REQUIRED: 'Last Name is required.',
  COUNTRY_CODE_REQUIRED: 'Country code is required.',
  COUNTRY_REQUIRED: 'Country is required',
  MUNICIPALITY_REQUIRED: 'Municipality is required',
  FROM_REQUIRED: 'From is required',
  TO_REQUIRED: 'To is required',
  GROUP_NAME_REQUIRED: 'Group name is required',
  DESCRIPTION_REQUIRED: 'Description is required',
  PHONE_REQUIRED: 'Phone is required.',
  PASSWORD_REQUIRED: 'Password is required.',
  COMMENT_ADDED: 'Comment successfully added',
  COMMENT_REQUIRED: 'Comment required',
  PHONE_NUMBER_NOT_VERIFIED: 'Phone number not verified',
  INVALID_VERIFICATION_CODE: 'Verification code is invalid',
  PHONE_NUMBER_VERIFIED: 'Phone number verified',
  SEAT_REQUIRED: 'No. of seat must be atleast one',
  DATE_REQUIRED: 'Date is required.',
  TIME_REQUIRED: 'Time is required.',
};
