# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Skjutsgruppen' do
  pod 'Fabric'
  pod 'Crashlytics'
#    pod 'Digits'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'TwitterKit', '1.12.1'


  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'CxxBridge', # Include this for RN >= 0.47
  'BatchedBridge', # Include this for RN <= 0.46
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTSettings',
  'RCTVibration'
  ]
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk/ios'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # react-native-maps dependencies
#  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
#  pod 'GooglePlaces'
#  pod 'GooglePlacePicker

#braintree
  pod 'BraintreeDropIn'

  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == "React"
            target.remove_from_project
        end
    end
end
