# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Skjutsgruppen' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # # Pods for Skjutsgruppen
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # target 'Skjutsgruppen-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'SkjutsgruppenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Skjutsgruppen-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Skjutsgruppen-tvOS

  target 'Skjutsgruppen-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
